### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by 5igm** [Minecrell/ServerListPlus#127]
ServerListPlus-3.4.6-Universal
spongeforge-1.8.9-1890-4.2.0-BETA-1653
forge-1.8.9-11.15.1.1902-1.8.9-universal
```
[03:39:42] [Server thread/ERROR] [Sponge/]: Could not pass ClientConnectionEvent$Disconnect$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@23814430
java.lang.NullPointerException
	at net.minecrell.serverlistplus.sponge.SpongePlugin$LoginListener.onPlayerQuit(SpongePlugin.java:207) ~[SpongePlugin$LoginListener.class:?]
	at org.spongepowered.common.event.listener.DisconnectListener_LoginListener_onPlayerQuit29.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1653]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1653]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:184) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1653]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1653]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1653]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1653]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$0(NetHandlerPlayServer.java:439) [lm.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:704) [lm.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:449) [ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:183) [ll.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by Minecrell** [comment]
That error is not caused by ServerListPlus, but rather by SpongeForge. It doesn't cause any problems though so you can just ignore it.

See https://github.com/SpongePowered/SpongeForge/issues/527

**Comment by 5igm** [comment]
Thank you very much.
