### ISSUE TITLE
I cant view the hover text on the slots... BUG

### ISSUE THREAD

**Issue by PanchoGamerYTOFICIAL** [Minecrell/ServerListPlus#179]
When I put the cursor over the slots to see the text, this appears in the console:

```
[05:44:35 ERROR]: [ServerListPlus] Unhandled exception occured in onPacketSending(PacketEvent) for ServerListPlus
java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.wrappers.BukkitConverters$15.getSpecificValue(BukkitConverters.java:742) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$15.getSpecificValue(BukkitConverters.java:734) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:142) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:230) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.3.0]
        at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketSending(ProtocolLibHandler.java:80) ~[ServerListPlus-3.4.7-Bukkit-1.8.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:440) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.encode(ChannelInjector.java:247) [ProtocolLib.jar:4.3.0]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:111) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:253) [ProtocolLib.jar:4.3.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:657) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:715) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:650) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:657) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:715) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:705) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:740) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:241) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) [ProtocolLib.jar:4.3.0]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:132) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketStatusListener.a(PacketStatusListener.java:131) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketStatusInStart.a(SourceFile:23) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketStatusInStart.a(SourceFile:8) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:84) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.NetworkManager.channelRead0(NetworkManager.java:249) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.LegacyPingHandler.channelRead(SourceFile:94) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [BlackWhiteNETWORK.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: Unable to find a field null with the type com.google.gson.Gson in net.minecraft.server.v1_8_R1.PacketStatusOutServerInfo
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedServerPing.<clinit>(WrappedServerPing.java:71) ~[?:?]
        ... 64 more
[05:44:35 ERROR]: Parameters: 
  net.minecraft.server.v1_8_R1.PacketStatusOutServerInfo@15b36149[
    b=net.minecraft.server.v1_8_R1.ServerPing@6b33600d
  ]
```

Can u help me please?

**Comment by Minecrell** [comment]
This looks like a ProtocolLib issue. Please report it at https://github.com/dmulloy2/ProtocolLib/issues
