### ISSUE TITLE
[1.7.10] Error when Player loads the Server List message

### ISSUE THREAD

**Issue by ApertureDevelopment** [Minecrell/ServerListPlus#205]
I just installed SLP and enabled it ( 1.7.x release ) and in throws this error: 

```
>slp enable
[14:17:44 INFO]: [ServerListPlus] Enabling ServerListPlus...
[14:17:44 INFO]: [ServerListPlus] [Core] Reloading configuration...
[14:17:44 INFO]: [ServerListPlus] [Core] Loaded configuration: ServerStatusConf
[14:17:44 INFO]: [ServerListPlus] [Core] Loaded configuration: PluginConf
[14:17:44 INFO]: [ServerListPlus] ServerListPlus has been successfully enabled!
[14:17:59 ERROR]: [ServerListPlus] Unhandled exception occured in onPacketSending(PacketEvent) for ServerListPlus
java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:657) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:649) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:143) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:201) ~[ProtocolLib.jar:?]
        at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketSending(ProtocolLibHandler.java:77) ~[ServerListPlus-3.4.9-SNAPSHOT-Bukkit-1.7.X.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:633) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:609) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:385) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:434) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.encode(ChannelInjector.java:246) [ProtocolLib.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:111) [MessageToByteEncoder.class:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:251) [ProtocolLib.jar:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) [DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) [AbstractChannel.class:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:310) [ProtocolLib.jar:?]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:185) [ej.class:?]
        at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:159) [ej.class:?]
        at net.minecraft.server.network.NetHandlerStatusServer.func_147312_a(NetHandlerStatusServer.java:76) [nq.class:?]
        at net.minecraft.network.status.client.C00PacketServerQuery.func_148833_a(SourceFile:25) [kj.class:?]
        at net.minecraft.network.status.client.C00PacketServerQuery.func_148833_a(SourceFile:8) [kj.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:137) [ej.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:353) [ej.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:261) [ProtocolLib.jar:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at net.minecraft.network.PingResponseHandler.channelRead(SourceFile:94) [mz.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException: source class cannot be NULL
        at guava10.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204) ~[Preconditions.class:1.7.10-R0.1-SNAPSHOT]
        at com.comphenix.protocol.reflect.ExactReflection.<init>(ExactReflection.java:18) ~[?:?]
        at com.comphenix.protocol.reflect.ExactReflection.fromClass(ExactReflection.java:38) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.Accessors.getMethodAccessor(Accessors.java:229) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedServerPing.<clinit>(WrappedServerPing.java:80) ~[?:?]
        ... 58 more
[14:17:59 ERROR]: Parameters:
  net.minecraft.network.status.server.S00PacketServerInfo@15d260f8[
    field_149296_b=net.minecraft.network.ServerStatusResponse@54a3c5b3
    timestamp=1523189879861
  ]

[14:18:32 ERROR]: [ServerListPlus] Unhandled exception occured in onPacketSending(PacketEvent) for ServerListPlus
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedServerPing
        at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:657) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:649) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:143) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:201) ~[ProtocolLib.jar:?]
        at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketSending(ProtocolLibHandler.java:77) ~[ServerListPlus-3.4.9-SNAPSHOT-Bukkit-1.7.X.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:633) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:609) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:385) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:434) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.encode(ChannelInjector.java:246) [ProtocolLib.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:111) [MessageToByteEncoder.class:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:251) [ProtocolLib.jar:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) [DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) [AbstractChannel.class:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:310) [ProtocolLib.jar:?]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:185) [ej.class:?]
        at net.minecraft.network.NetworkManager.func_150725_a(NetworkManager.java:159) [ej.class:?]
        at net.minecraft.server.network.NetHandlerStatusServer.func_147312_a(NetHandlerStatusServer.java:76) [nq.class:?]
        at net.minecraft.network.status.client.C00PacketServerQuery.func_148833_a(SourceFile:25) [kj.class:?]
        at net.minecraft.network.status.client.C00PacketServerQuery.func_148833_a(SourceFile:8) [kj.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:137) [ej.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:353) [ej.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:261) [ProtocolLib.jar:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at net.minecraft.network.PingResponseHandler.channelRead(SourceFile:94) [mz.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[14:18:32 ERROR]: Parameters:
  net.minecraft.network.status.server.S00PacketServerInfo@6fecb03a[
    field_149296_b=net.minecraft.network.ServerStatusResponse@7d6be07c
    timestamp=1523189912185
  ]

>
```

If I am the one doing something wrong, please tell me

**Comment by Minecrell** [comment]
Looks like a ProtocolLib issue. You might be running a build of ProtocolLib that is incompatible with 1.7.10. Have you tried an older version?

**Comment by Minecrell** [comment]
Uh well, it might be due to that. I'm afraid I cannot help you with this issue, you can try contacting the ProtocolLib authors but I'm not sure if they still support such old versions.
