### ISSUE TITLE
NPE on Player Ping

### ISSUE THREAD

**Issue by adamlaughlin** [Minecrell/ServerListPlus#243]
Hey folks, love what the plugin helps me do - but I am seeing this error when a player tries to ping the server.  Edit @0217h EST:  It's only affecting one player.  I can not determine exactly why.

```
04.03 00:28:38 [Server] ERROR Could not pass event StandardPaperServerListPingEventImpl to ServerListPlus v3.4.8
04.03 00:28:38 [Server] INFO java.lang.NullPointerException: null
04.03 00:28:38 [Server] INFO at net.minecrell.serverlistplus.bukkit.BukkitPlugin.getFavicon(BukkitPlugin.java:246) ~[?:?]
04.03 00:28:38 [Server] INFO at net.minecrell.serverlistplus.bukkit.handlers.BukkitEventHandler$PingListener.onServerListPing(BukkitEventHandler.java:79) ~[?:?]
04.03 00:28:38 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor112.execute(Unknown Source) ~[?:?]
04.03 00:28:38 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:80) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at net.minecraft.server.v1_13_R2.PacketStatusListener.a(PacketStatusListener.java:131) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at net.minecraft.server.v1_13_R2.PacketStatusInStart.a(SourceFile:23) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at net.minecraft.server.v1_13_R2.PacketStatusInStart.a(SourceFile:8) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:156) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:145) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:31) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:154) ~[?:?]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) ~[?:?]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at net.minecraft.server.v1_13_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:120) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.2.jar:git-Paper-548]
04.03 00:28:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

Any thoughts?

**Comment by Minecrell** [comment]
Umm, can you post the full server log and your configuration? Does this happen several times or just once? Does it happen while starting the server?

**Comment by adamlaughlin** [comment]
I will reproduce it with only the plugins I always need enabled like LuckPerms, and if I can't do that, no worries.  I apologize for wasting your time, I believed this was happening to everyone when I first posted.

It's only one untrustworthy player after all, I should assume it was the result of a probably hacked client.
Thanks for being so _fast!_

**Comment by Minecrell** [comment]
No worries. Please comment here if you can reproduce it reliably. Thanks :)
