### ISSUE TITLE
Internal Error?

### ISSUE THREAD

**Issue by ItsSolace** [Minecrell/ServerListPlus#244]
I'm sure this is just because I've done something stupid, but whenever I try to run /slp enable, I get an internal error. I also noticed that in the /pl it's actually red. So I have no idea what's happening. Here is my config:

```
       _____                     __    _     _   _____ _
      |   __|___ ___ _ _ ___ ___|  |  |_|___| |_|  _  | |_ _ ___
      |__   | -_|  _| | | -_|  _|  |__| |_ -|  _|   __| | | |_ -|
      |_____|___|_|  \_/|___|_| |_____|_|___|_| |__|  |_|___|___|
  
  ServerListPlus v3.4.8 - http://git.io/slp
 
  More information is available in the Wiki: http://git.io/slp-wiki
 
 
  This is the section where you can customize your server status ping!
   - Default is the section for the status used when the player name is unknown.
     Personalized is used if the client has already joined the server once.
     Use %player% as placeholder for the player's name.
 
  Features:
   - Description (MotD): A short status message for your server, max. 2 lines.
   - Players:
     - Hover: The player hover message that is displayed if you hover the player count.
     - Slots: Custom player slot formatting, see http://git.io/slp-slots
   - Favicon:
     - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
     - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
  
   More features are explained in the Wiki: http://git.io/slp-config
  
  Usage:
   - Add multiple entries for random messages.
   - Save the file with valid UTF-8 encoding for special characters.
   - Available placeholders:
     - Player name: %player%
     - Player count: %online%, %max%, %online@server% %online@world%
     - Random online player name: %random_player%
 --- !Status
 Default:
   Description:
   - |-
     &9&lMyth&8&lMC
     &fClassic SkyBlock With A Few Twists!
   - |-
        &9&lMyth&8&lMC
     &fClassic SkyBlock With A Few Twists!
   Players:
     Hover:
     - |-
       &9&lMyth&8&lMC &fcurrently has:
       &9&l%online% &fplayers online!
 Personalized:
   Description:
   - |-
     &9&lMyth&8&lMC
     &fClassic SkyBlock With A Few Twists!
   - |-
     &9&lMyth&8&lMC
     &fClassic SkyBlock With A Few Twists!
   Players:
     Hover:
     - |-
       &9&lMyth&8&lMC &fcurrently has:
       &9&l%online% &fplayers online!
 
  Stats: Enable/disable sending plugin statistics.
  PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
    - Persistence can be disabled with the toggle in the Storage section.
  Samples: Toggle using multiple player infos for the player hover message.
      May prevent the annoying ... and x more ... message for bigger servers
      DynamicPlayers is special and aligns the number with the number of
      random players used in placeholders.
  Unknown: Placeholder replacement if the real value is unknown.
  Favicon: Options for the creation / downloading of favicons:
   - RecursiveFolderSearch: Also search for favicons in sub directories.
   - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
   - ResizeStrategy: The strategy used to resize too small or too big favicons.
       NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
 --- !Plugin
 Stats: false
 PlayerTracking:
   Enabled: false
   Storage: !JSONStorage
     Enabled: true
     SaveDelay: 5m
 Samples:
   Multiple: false
   DynamicPlayers: false
 Unknown:
   PlayerName: player
   PlayerCount: ???
   Date: ???
 Favicon:
   Timeout: 10s
   RecursiveFolderSearch: false
   ResizeStrategy: SCALE
 
```
Here is the error it gives me in the console:

> [16:44:12] [Server thread/WARN]: Unexpected exception while parsing console command "slp enable"
> org.bukkit.command.CommandException: Cannot execute command 'slp' in plugin ServerListPlus v3.4.8 - plugin is disabled.
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
> at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
> at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:687) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
> at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
> at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
> at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
> at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
>

**Comment by Minecrell** [comment]
Please post the full log.

**Comment by ItsSolace** [comment]
> [Minecraft Panel] Connecting to Web Console.. please wait..
[Minecraft Panel] Web console connected!
tialsChat] Enabling EssentialsChat v2.16.0.3
[17:27:59] [Server thread/INFO]: [JumpPads] Enabling JumpPads v1.17.0
[17:27:59] [Server thread/INFO]: [EssentialsAntiBuild] Enabling EssentialsAntiBuild v2.16.0.3
[17:27:59] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.16.0.3
[17:27:59] [Server thread/INFO]: [EssentialsXMPP] Enabling EssentialsXMPP v2.16.0.3
[17:27:59] [Server thread/WARN]: config broken for xmpp
[17:27:59] [Server thread/INFO]: [ServerListPlus] Enabling ServerListPlus v3.4.8
[17:27:59] [Server thread/INFO]: [ServerListPlus] [Core] Reloading configuration...
[17:27:59] [Server thread/WARN]: [ServerListPlus] [Core] Unable to parse a part of the configuration. Make sure the YAML syntax is valid!
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'reader', line 36, column 3:
Description:
^
expected <block end>, but found '<anchor>'
in 'reader', line 42, column 5:
&fClassic SkyBlock With A Few Tw ... 
^

at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:123) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:547) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecrell.serverlistplus.core.ConfigurationManager.reload(ConfigurationManager.java:96) ~[?:?]
at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:186) ~[?:?]
at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:135) ~[?:?]
at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:87) ~[?:?]
at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:139) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:807) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.Bukkit.reload(Bukkit.java:570) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[17:27:59] [Server thread/ERROR]: [ServerListPlus] [Core] Unable to parse the configuration. Make sure the YAML syntax is correct!
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'reader', line 35, column 1:
Default:
^
expected <block end>, but found '<anchor>'
in 'reader', line 42, column 5:
&fClassic SkyBlock With A Few Tw ... 
^

at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:68) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:112) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.yaml.snakeyaml.Yaml$1.hasNext(Yaml.java:542) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecrell.serverlistplus.core.ConfigurationManager.reload(ConfigurationManager.java:93) ~[?:?]
at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:186) ~[?:?]
at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:135) ~[?:?]
at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:87) ~[?:?]
at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:139) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:807) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.Bukkit.reload(Bukkit.java:570) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[17:27:59] [Server thread/INFO]: [ServerListPlus] Please fix the error before restarting the server!
[17:27:59] [Server thread/INFO]: [ServerListPlus] Disabling ServerListPlus v3.4.8
[17:27:59] [Server thread/ERROR]: Error occurred while disabling ServerListPlus v3.4.8 (Is it up to date?)
java.lang.NullPointerException: null
at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:157) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecrell.serverlistplus.bukkit.BukkitPluginBase.disablePlugin(BukkitPluginBase.java:46) ~[?:?]
at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:143) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:807) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.Bukkit.reload(Bukkit.java:570) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[17:27:59] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:27:59] [Server thread/INFO]: ItsSolace: Reload complete.
[17:27:59] [Server thread/WARN]: ItsSolace moved too quickly! -14.886619412429013,1.5244240882136637,0.3028162277292239
[17:27:59] [Server thread/INFO]: [BentoBox] Added world BSkyBlock (NORMAL)
[17:27:59] [Server thread/INFO]: 
____ _ ____
| _ \ | | | _ \ by tastybento and Poslovitch
| |_) | ___ _ __ | |_ ___ | |_) | _____ __ 2017 - 2019
| _ < / _ \ '_ \| __/ _ \| _ < / _ \ \/ /
| |_) | __/ | | | || (_) | |_) | (_) > < v1.3.1
|____/ \___|_| |_|\__\___/|____/ \___/_/\_\ Loaded in 1128ms.

[17:27:59] [Server thread/INFO]: [JumpPads] CleanUp found no JumpPads to delete!

**Comment by Minecrell** [comment]
The problem is

```yaml
   - |-
        &9&lMyth&8&lMC
     &fClassic SkyBlock With A Few Twists!
```
in your configuration.

You will either need to remove the spaces:

```yaml
   - |-
     &9&lMyth&8&lMC
     &fClassic SkyBlock With A Few Twists!
```

or add a color code before the spaces

```yaml
   - |-
     &9   &lMyth&8&lMC
     &fClassic SkyBlock With A Few Twists!
```

**Comment by ItsSolace** [comment]
It worked! Thank you so much!
