### ISSUE TITLE
Plugin is broken on 1.15

### ISSUE THREAD

**Issue by eirikh1996** [Minecrell/ServerListPlus#270]
I recently upped my server from 1.14.4 to 1.15.1, and now this happens:

[ERROR] .... [ServerListPlus] An internal error occurred while loading the core!

com.comphenix.protocol.reflect.FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.

at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]

at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]

at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:57) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59) ~[?:?]

at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70) ~[?:?]

at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271) ~[?:?]

at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:259) ~[?:?]

at com.comphenix.protocol.concurrency.PacketTypeSet.getPacketClass(PacketTypeSet.java:82) ~[?:?]

at com.comphenix.protocol.concurrency.PacketTypeSet.addType(PacketTypeSet.java:35) ~[?:?]

at com.comphenix.protocol.injector.spigot.AbstractPacketInjector.addPacketHandler(AbstractPacketInjector.java:30) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.enablePacketFilters(PacketFilterManager.java:634) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:390) ~[?:?]

at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler.register(ProtocolLibHandler.java:154) ~[?:?]

at net.minecrell.serverlistplus.bukkit.BukkitPlugin.statusChanged(BukkitPlugin.java:446) ~[?:?]

at net.minecrell.serverlistplus.core.status.StatusManager.reload(StatusManager.java:112) ~[?:?]

at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:191) ~[?:?]

at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:135) ~[?:?]

at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:87) ~[?:?]

at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:139) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-23]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-23]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-23]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-23]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-23]

at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-23]

at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-23]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-23]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

[INFO] .... [ServerListPlus] Disabling ServerListPlus v3.4.8

**Comment by Minecrell** [comment]
This mainly just means that ProtocolLib needs an update. Try updating it to the latest development build.

Since you are using Paper, I would highly recommend installing the latest development build of ServerListPlus from https://ci.codemc.io/job/Minecrell/job/ServerListPlus/
On Paper, SLP provides full functionality without ProtocolLib, so you could remove ProtocolLib entirely instead.
