### ISSUE TITLE
YAML syntax error

### ISSUE THREAD

**Issue by Bublelift** [Minecrell/ServerListPlus#273]
[07:20:30] [Server thread/WARN]: [ServerListPlus] [Core] Unable to parse a part of the configuration. Make sure the YAML syntax is valid!
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=Default for JavaBean=net.minecrell.serverlistplus.core.config.ServerStatusConf@52b0ca05
 in 'reader', line 34, column 5:
    --- !Status
        ^
Cannot create property=Players for JavaBean=net.minecrell.serverlistplus.core.config.PersonalizedStatusConf$StatusConf@1fbfcd71
 in 'reader', line 36, column 3:
      Description:
      ^
No suitable constructor with 1 arguments found for class net.minecrell.serverlistplus.core.config.PersonalizedStatusConf$StatusConf$PlayersConf
 in 'reader', line 41, column 5:
        - '&f&l1.13.2 - 1.15.1 &b&l%onli ... 
        ^

 in 'reader', line 36, column 3:
      Description:
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:270) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:127) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:547) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecrell.serverlistplus.core.ConfigurationManager.reload(ConfigurationManager.java:96) ~[?:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:186) ~[?:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:135) ~[?:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:87) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:139) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:859) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.Bukkit.reload(Bukkit.java:638) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:55) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=Players for JavaBean=net.minecrell.serverlistplus.core.config.PersonalizedStatusConf$StatusConf@1fbfcd71
 in 'reader', line 36, column 3:
      Description:
      ^
No suitable constructor with 1 arguments found for class net.minecrell.serverlistplus.core.config.PersonalizedStatusConf$StatusConf$PlayersConf
 in 'reader', line 41, column 5:
        - '&f&l1.13.2 - 1.15.1 &b&l%onli ... 
        ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:270) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:283) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:246) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	... 35 more
Caused by: org.yaml.snakeyaml.error.YAMLException: No suitable constructor with 1 arguments found for class net.minecrell.serverlistplus.core.config.PersonalizedStatusConf$StatusConf$PlayersConf
	at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:584) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:247) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:283) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:246) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	... 35 more
[07:20:30] [Server thread/INFO]: [ServerListPlus] [Core] Loaded configuration: PluginConf
[07:20:30] [Server thread/WARN]: [ServerListPlus] [Core] Could not load all configurations from the configuration file. Please make sure the syntax is correct. Type '/slp save' if you want to add the missing parts.

**So I added the missing parts using /slp save, but I still cannot even save the config file, because it's showing yaml syntax error in line:
--- !Plugin<----**

Full config here
#      _____                     __    _     _   _____ _
#     |   __|___ ___ _ _ ___ ___|  |  |_|___| |_|  _  | |_ _ ___
#     |__   | -_|  _| | | -_|  _|  |__| |_ -|  _|   __| | | |_ -|
#     |_____|___|_|  \_/|___|_| |_____|_|___|_| |__|  |_|___|___|
# 
# ServerListPlus v3.4.8 - http://git.io/slp

# More information is available in the Wiki: http://git.io/slp-wiki

# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
--- !Status
Default:
  Description:
  - |-
    &aA Minecraft Server.
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &aA Minecraft Server.
    &eWe have updated our server to &lMinecraft 1.13&e!
  Players:
    Hover:
    - |-
      &aWelcome to &lA Minecraft Server&a!
      &aCurrently &e&l%online% &aplayers are playing on our server!
Personalized:
  Description:
  - |-
    &aA Minecraft Network. &7|  &eHello, &l%player%!
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &aA Minecraft Network. &7|  &eHello, &l%player%!
    &eWe have updated our server to &lMinecraft 1.8&e!
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online% &aplayers are playing on our server!

# Stats: Enable/disable sending plugin statistics.
# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# Samples: Toggle using multiple player infos for the player hover message.
#     May prevent the annoying ... and x more ... message for bigger servers
#     DynamicPlayers is special and aligns the number with the number of
#     random players used in placeholders.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
Stats: true
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
Samples:
  Multiple: false
  DynamicPlayers: false
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE

Yes, it's the default config and I can't use it, because of syntax error

**Comment by Bublelift** [comment]
New console log:
[14:44:55 INFO]: [ServerListPlus] Reloading configuration...
[14:44:55 INFO]: [ServerListPlus] [Core] Reloading configuration...
[14:44:55 ERROR]: [ServerListPlus] [Core] Unable to parse the configuration. Make sure the YAML syntax is correct!
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:72) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:112) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.yaml.snakeyaml.Yaml$1.hasNext(Yaml.java:542) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecrell.serverlistplus.core.ConfigurationManager.reload(ConfigurationManager.java:93) ~[?:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:186) ~[?:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.executeCommand(ServerListPlusCore.java:255) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin$ServerListPlusCommand.onCommand(BukkitPlugin.java:171) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[?:1.8.0_201]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:1.8.0_201]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_201]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_201]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_201]
	at java.io.BufferedReader.read1(BufferedReader.java:212) ~[?:1.8.0_201]
	at java.io.BufferedReader.read(BufferedReader.java:286) ~[?:1.8.0_201]
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183) ~[Paper-1.13.2-b624.jar:git-Paper-624]
	... 25 more
[14:44:55 INFO]: [ServerListPlus] An internal error occurred while reloading the configuration.

stil the problem is line: --- !Plugin

**Comment by Minecrell** [comment]
Can you post the configuration as https://gist.github.com/? It's completely unreadable the way you have posted it...

**Comment by Bublelift** [comment]
**Yeah, surely i posted it intentionaly, so you couldn't read it :)))**
**All you had to do was paste it to your notepad and everything is clear**

ServerListPlus v3.4.8 - http://git.io/slp
More information is available in the Wiki: http://git.io/slp-wiki
This is the section where you can customize your server status ping!
- Default is the section for the status used when the player name is unknown.
Personalized is used if the client has already joined the server once.
Use %player% as placeholder for the player's name.
Features:
- Description (MotD): A short status message for your server, max. 2 lines.
- Players:
- Hover: The player hover message that is displayed if you hover the player count.
- Slots: Custom player slot formatting, see http://git.io/slp-slots
- Favicon:
- Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
- Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
More features are explained in the Wiki: http://git.io/slp-config
Usage:
- Add multiple entries for random messages.
- Save the file with valid UTF-8 encoding for special characters.
- Available placeholders:
- Player name: %player%
- Player count: %online%, %max%, %online@server% %online@world%
- Random online player name: %random_player%

--- !Status
Default:
Description:

    |-
    &aA Minecraft Server.
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
    |-
    &aA Minecraft Server.
    &eWe have updated our server to &lMinecraft 1.13&e!
    Players:
    Hover:
        |-
        &aWelcome to &lA Minecraft Server&a!
        &aCurrently &e&l%online% &aplayers are playing on our server!
        Personalized:
        Description:
    |-
    &aA Minecraft Network. &7| &eHello, &l%player%!
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
    |-
    &aA Minecraft Network. &7| &eHello, &l%player%!
    &eWe have updated our server to &lMinecraft 1.8&e!
    Players:
    Hover:
        |-
        &aWelcome back, &l%player%&a!
        &aCurrently &e&l%online% &aplayers are playing on our server!

Stats: Enable/disable sending plugin statistics.
PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
- Persistence can be disabled with the toggle in the Storage section.
Samples: Toggle using multiple player infos for the player hover message.
May prevent the annoying ... and x more ... message for bigger servers
DynamicPlayers is special and aligns the number with the number of
random players used in placeholders.
Unknown: Placeholder replacement if the real value is unknown.
Favicon: Options for the creation / downloading of favicons:
- RecursiveFolderSearch: Also search for favicons in sub directories.
- SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
- ResizeStrategy: The strategy used to resize too small or too big favicons.
NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)

--- !Plugin
Stats: true
PlayerTracking:
Enabled: true
Storage: !JSONStorage
Enabled: true
SaveDelay: 5m
Samples:
Multiple: false
DynamicPlayers: false
Unknown:
PlayerName: player
PlayerCount: ???
Date: ???
Favicon:
Timeout: 10s
RecursiveFolderSearch: false
ResizeStrategy: SCALE

**Comment by Minecrell** [comment]
Still not very readable. Posting it here removes the indentation.

**Comment by Bublelift** [comment]
Well maybe learn to read, I don't know

**Comment by Bublelift** [comment]
Should I prepare it as a fcking .doc file perfectly edited just for you?

**Comment by Minecrell** [comment]
Sorry, I don't think I should help you with such an attitude. I merely asked you to provide a plain text copy of your configuration, like this: https://gist.github.com/Minecrell/c7e538c8dd59b53f45bbbb194d83629f

If you don't want help, don't ask for it.

**Comment by Minecrell** [comment]
I fixed all your posts for you. Now they are properly readable.

- The error in your original issue (https://github.com/Minecrell/ServerListPlus/issues/273#issue-550605191) was some syntax error, but the configuration you posted does not contain it (it's just the default configuration as you mentioned).

- The second error you posted (https://github.com/Minecrell/ServerListPlus/issues/273#issuecomment-575631694) means that the configuration was saved with the wrong charset. It must be stored as UTF-8 to work properly.

You can try removing the `plugins/ServerListPlus` folder. That should restore the original default configuration as-is and should work just fine. If not, please post the log from the initial start. Thanks.
