### ISSUE TITLE
Error w/ ProtocolLib stuff

### ISSUE THREAD

**Issue by lolw0tm8** [Minecrell/ServerListPlus#286]
Hello, this error sometimes pops in my console, not sure why, it has something to do with ProtocolLib?

```
[21:58:34 ERROR]: [ServerListPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for ServerListPlus
java.lang.NullPointerException
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:695) ~[ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:684) ~[ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.5.0]
at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketReceiving(ProtocolLibHandler.java:63) ~[ServerListPlus-3.4.8-Universal.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533) [ProtocolLib.jar:4.5.0]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:205) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [server.jar:1.8.8-R0.1-SNAPSHOT]
at protocolsupport.protocol.core.timeout.SimpleReadTimeoutHandler.channelInactive(SimpleReadTimeoutHandler.java:33) [ProtocolSupport-1.8.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:1.8.8-R0.1-SNAPSHOT]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> [21:58:34 ERROR]: Parameters:
net.minecraft.server.v1_8_R3.PacketHandshakingInSetProtocol@18096cdf[
a=0
hostname=
port=67
d=<null>
> [21:58:34 ERROR]: [ServerListPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for ServerListPlus
java.lang.NullPointerException
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:695) ~[ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:684) ~[ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.5.0]
at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketReceiving(ProtocolLibHandler.java:63) ~[ServerListPlus-3.4.8-Universal.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533) [ProtocolLib.jar:4.5.0]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:205) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [server.jar:1.8.8-R0.1-SNAPSHOT]
at protocolsupport.protocol.core.timeout.SimpleReadTimeoutHandler.channelInactive(SimpleReadTimeoutHandler.java:33) [ProtocolSupport-1.8.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [server.jar:1.8.8-R0.1-SNAPSHOT]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:1.8.8-R0.1-SNAPSHOT]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> [21:58:34 ERROR]: Parameters:
net.minecraft.server.v1_8_R3.PacketHandshakingInSetProtocol@194d6042[
a=0
hostname=
port=67
d=<null>
```

**Comment by Minecrell** [comment]
Looks like a ProtocolLib issue to me.

**Comment by lolw0tm8** [comment]
It's from ServerListPlus tho

**Comment by Minecrell** [comment]
Not really, SLP is just attempting to read the packets and then it errors somewhere in ProtocolLib...

**Comment by lolw0tm8** [comment]
Why it does so though? Do I need special version of ProtocolLib for it to not error?
