### ISSUE TITLE
onPacketSending(PacketEvent) (Don't know how to turn..)

### ISSUE THREAD

**Issue by mrfloris** [Minecrell/ServerListPlus#305]
https://hasteb.in/aravejeb.swift

```
ServerListPlus version 3.5.0-SNAPSHOT
Paper version git-Paper-138 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

**Comment by mrfloris** [comment]
I don't know where that went, hastebin doesn't seem to exist anymore..
```
[10:55:37 ERROR]: [ServerListPlus] Unhandled exception occured in onPacketSending(PacketEvent) for ServerListPlus
java.lang.RuntimeException: An internal error occured.
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.deserialize(WrappedChatComponent.java:62) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.fromJson(WrappedChatComponent.java:93) ~[?:?]
        at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketSending(ProtocolLibHandler.java:114) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:437) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247) ~[?:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[patched_1.16.3.jar:git-Paper-202]
        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[patched_1.16.3.jar:git-Paper-202]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
        at net.minecraft.server.v1_16_R2.NetworkManager.b(NetworkManager.java:268) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.NetworkManager.dispatchPacket(NetworkManager.java:244) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.NetworkManager.sendPacket(NetworkManager.java:220) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.NetworkManager.sendPacket(NetworkManager.java:206) ~[patched_1.16.3.jar:git-Paper-202]
        at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:109) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.PacketStatusListener.a(PacketStatusListener.java:136) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.PacketStatusInStart.a(SourceFile:22) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.PacketStatusInStart.a(SourceFile:8) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:159) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.NetworkManager.channelRead0(NetworkManager.java:148) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.NetworkManager.channelRead0(NetworkManager.java:30) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-202]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[patched_1.16.3.jar:git-Paper-202]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.16.3.jar:git-Paper-202]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.google.gson.JsonParseException: Don't know how to turn {"value":[{"text":"Click to open url"}]} into a Component
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:205) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:101) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.Gson.fromJson(Gson.java:925) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:364) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChatHoverable$EnumHoverAction.a(SourceFile:337) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChatHoverable.a(SourceFile:94) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChatModifier$ChatModifierSerializer.b(ChatModifier.java:288) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChatModifier$ChatModifierSerializer.deserialize(ChatModifier.java:259) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChatModifier$ChatModifierSerializer.deserialize(ChatModifier.java:239) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:237) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:233) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:101) ~[patched_1.16.3.jar:git-Paper-202]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChatDeserializer.a(SourceFile:493) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChatDeserializer.a(SourceFile:517) ~[patched_1.16.3.jar:git-Paper-202]
        at jdk.internal.reflect.GeneratedMethodAccessor231.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[?:?]
        ... 75 more
[10:55:37 ERROR]: Parameters:
  net.minecraft.server.v1_16_R2.PacketStatusOutServerInfo@7229cdbc[
    b=net.minecraft.server.v1_16_R2.ServerPing@5ef5ad8e
  ]

```
But here's another one.

**Comment by mrfloris** [comment]
```
> ver
[11:10:18 INFO]: This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[11:10:18 INFO]: Checking version, please wait...
[11:10:18 INFO]: Previous version: git-Paper-198 (MC: 1.16.3)
[11:10:18 INFO]: You are running the latest version
> ver ServerListPlus
[11:10:20 INFO]: ServerListPlus version 3.5.0-SNAPSHOT
[11:10:20 INFO]: A flexible Minecraft plugin to customize the appearance of your server in the server list
[11:10:20 INFO]: Website: https://git.io/slp
[11:10:20 INFO]: Author: Minecrell (https://github.com/Minecrell)
>
```

**Comment by Minecrell** [comment]
`ProtocolLibHandler.java:114` cannot cause an exception:

https://github.com/Minecrell/ServerListPlus/blob/ee045c6169e65743aa35596a77a86e834297e9de/Bukkit/src/main/java/net/minecrell/serverlistplus/bukkit/handlers/ProtocolLibHandler.java#L114

Also I see no usage of `WrappedChatComponent.fromJson` in ServerListPlus. You seem to be running some forked version :thinking: 

If you do, please ask them for support :)

**Comment by Minecrell** [comment]
I guess this is the Minebench fork. That would be an issue for @Phoenix616 then. I will close this here, thanks :)

https://github.com/Minecrell/ServerListPlus/blob/5b9bf898795db64d995f70b11cbb94dd6d63c768/Bukkit/src/main/java/net/minecrell/serverlistplus/bukkit/handlers/ProtocolLibHandler.java#L114
