### ISSUE TITLE
NPE on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [Minecrell/ServerListPlus#350]
Spigot 1.16.5-3087
ServerListPlus-bukkit 3.5.0-b490

On server start-up
```
[07:52:53] [Server thread/INFO]: [ServerListPlus] Enabling ServerListPlus v3.5.0-SNAPSHOT
[07:52:53] [Server thread/ERROR]: [ServerListPlus] [Core] Unable to load plugin version information from JAR.
java.lang.NullPointerException: inStream parameter is null
        at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
        at java.util.Properties.load(Properties.java:407) ~[?:?]
        at net.minecrell.serverlistplus.core.CoreDescription.load(CoreDescription.java:70) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:100) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:91) ~[?:?]
        at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:156) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5-3087.jar:3087-Spigot-9fb885e-a0149bf]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
SLP continues to enable
```
[07:52:53] [Server thread/INFO]: [ServerListPlus] [Core] Reloading configuration...
[07:52:53] [Server thread/INFO]: [ServerListPlus] [Core] Loaded configuration: ServerStatusConf
[07:52:53] [Server thread/INFO]: [ServerListPlus] [Core] Loaded configuration: PluginConf
[07:52:53] [Server thread/INFO]: [ServerListPlus] Successfully loaded!
[07:52:53] [Server thread/INFO]: [ServerListPlus] ServerListPlus v3.5.0-SNAPSHOT enabled.
[07:53:37] [Server thread/INFO]: [ServerListPlus] [Core] Cleaning favicons cache...
[07:53:37] [Server thread/INFO]: [ServerListPlus] Successfully cleaned up favicons cache.
[07:53:37] [Server thread/INFO]: [ServerListPlus] Reloading configuration...
[07:53:37] [Server thread/INFO]: [ServerListPlus] [Core] Reloading configuration...
[07:53:37] [Server thread/INFO]: [ServerListPlus] [Core] Loaded configuration: ServerStatusConf
[07:53:37] [Server thread/INFO]: [ServerListPlus] [Core] Loaded configuration: PluginConf
[07:53:37] [Server thread/INFO]: [ServerListPlus] Configuration successfully reloaded!
```
and the MOTD is correct.

**Comment by Minecrell** [comment]
I cannot reproduce this. Is the JAR damaged maybe? What is your Java version?

**Comment by SlimeDog** [comment]
Java 11.0.11

On subsequent server start-ups -- lots of plugin updates were dropped over the last two hours -- the error is not encountered.
