### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to serverlistplus

### ISSUE THREAD

**Issue by prototype464** [Minecrell/ServerListPlus#369]
This error is displayed in console upon booting up Velocity (3.0.0):

[18:43:09 ERROR]: Couldn't pass ProxyInitializeEvent to serverlistplus
java.lang.NoSuchMethodError: 'void com.velocitypowered.api.command.CommandManager.register(com.velocitypowered.api.command.Command, java.lang.String[])'
        at net.minecrell.serverlistplus.velocity.VelocityPlugin.initialize(VelocityPlugin.java:128) ~[?:?]
        at net.minecrell.serverlistplus.velocity.Lmbda$15.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.0.1-SNAPSHOT (git-f79736b8-b42)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:589) ~[velocity.jar:3.0.1-SNAPSHOT (git-f79736b8-b42)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:470) ~[velocity.jar:3.0.1-SNAPSHOT (git-f79736b8-b42)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Minecrell** [comment]
Try using the latest SLP development builds from https://ci.codemc.io/job/Minecrell/job/ServerListPlus/

**Comment by prototype464** [comment]
> 
> 
> Try using the latest SLP development builds from https://ci.codemc.io/job/Minecrell/job/ServerListPlus/

Issue fixed, using #499 (latest)
Thanks!
