### ISSUE TITLE
players list could't work

### ISSUE THREAD

**Issue by Cloudwhile** [Minecrell/ServerListPlus#407]
# players list could't work
- Plugins: SimpleTpa, LuckPerms, LoginManager, Essentials, EssentialsChat, PlaceholderAPI, ProtocolLib, AuthMe, FastLogin, ServerListPlus
- Server Core: Spigot
- MC Version: 1.20.1
- SLP Version: 3.5.1-SNAPSHOT
- config.yml:
  
![image](https://github.com/Minecrell/ServerListPlus/assets/86512509/b4ed68ef-2ead-402e-b429-6212a361bc12)
- 
![image](https://github.com/Minecrell/ServerListPlus/assets/86512509/16e03965-587b-4c27-a087-fefa2b3bb887)
- no errors or warnings on the console.

**Comment by Cloudwhile** [comment]
# New wrong notice

[21:37:28 ERROR] [Minecraft]: [ServerListPlus] Unhandled exception occurred in onPacketSending(PacketEvent) for ServerListPlus
java.lang.IllegalStateException: Unable to construct new instance using public net.minecraft.network.protocol.status.ServerStatus(net.minecraft.network.chat.Component,java.util.Optional,java.util.Optional,java.util.Optional,boolean,java.util.Optional)
        at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:21) ~[?:?]
        at com.comphenix.protocol.wrappers.ping.ServerPingRecord.getHandle(ServerPingRecord.java:330) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedServerPing.getHandle(WrappedServerPing.java:320) ~[?:?]
        at com.comphenix.protocol.wrappers.Converters$3.getGeneric(Converters.java:108) ~[?:?]
        at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:55) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:358) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:322) ~[?:?]
        at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketSending(ProtocolLibHandler.java:141) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.processPacketOutbound(NettyChannelProxy.java:266) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:223) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[?:?]
        at net.minecraft.network.Connection.m_243087_(ConnectionMixin.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.network.Connection.m_129520_(ConnectionMixin.java:210) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.network.Connection.m_243124_(ConnectionMixin.java:189) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.network.Connection.m_129512_(ConnectionMixin.java:183) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.server.network.ServerStatusPacketListenerImpl.redirect$zgf000$arclight$handleServerPing(ServerStatusNetHandlerMixin.java:560) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.server.network.ServerStatusPacketListenerImpl.m_6733_(ServerStatusNetHandlerMixin.java:40) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.network.protocol.status.ServerboundStatusRequestPacket.m_5797_(ServerboundStatusRequestPacket.java:19) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.network.protocol.status.ServerboundStatusRequestPacket.m_5797_(ServerboundStatusRequestPacket.java:6) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.network.Connection.m_129517_(ConnectionMixin.java:174) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.network.Connection.channelRead0(ConnectionMixin.java:159) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at net.minecraft.network.Connection.channelRead0(ConnectionMixin.java:50) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:28) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:95) ~[server-1.20.1-20230612.114412-srg.jar%23243!/:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar%23117!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23120!/:4.1.82.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23120!/:4.1.82.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23120!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: array is not of length 6
        at java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(MethodHandleStatics.java:167) ~[?:?]
        at java.lang.invoke.MethodHandleImpl.checkSpreadArgument(MethodHandleImpl.java:584) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:19) ~[?:?]
        ... 69 more

**Comment by Cloudwhile** [comment]
[21:37:29 ERROR] [Minecraft]: Parameters: 
  net.minecraft.network.protocol.status.ClientboundStatusResponsePacket@5cbcba00[
    f_134886_=ServerStatus[description=empty[siblings=[literal{Welcome to}[style={color=#45BF55,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{ Happy Room!
  }[style={color=#0288D1,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{S}[style={color=#FFBE00,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{e}[style={color=#FEB901,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{r}[style={color=#FEB403,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{v}[style={color=#FDAE04,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{e}[style={color=#FDA906,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{r}[style={color=#FCA407,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{ }[style={color=#FC9F09,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{r}[style={color=#FB9A0A,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{e}[style={color=#FB940B,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{q}[style={color=#FA8F0D,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{u}[style={color=#FA8A0E,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{i}[style={color=#F98510,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{r}[style={color=#F98011,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{e}[style={color=#F87B13,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{s}[style={color=#F87514,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{ }[style={color=#F77015,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{p}[style={color=#F76B17,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{a}[style={color=#F66618,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{c}[style={color=#F6611A,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{k}[style={color=#F55B1B,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{ }[style={color=#F4511E,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{Happy Room }[style={color=yellow,bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{Version: 1.0.2}[style={color=red,!bold,!italic,!underlined,!strikethrough,!obfuscated}]]], players=Optional[Players[max=10, online=1, sample=[com.mojang.authlib.GameProfile@7f12b961[id=b6c01ab3-5050-431f-8757-7dc921c33b91,name=Zz1ing_ju,properties={textures=[com.mojang.authlib.properties.Property@4cb20b58]},legacy=false]]]], version=Optional[Version[name=forge arclight/Trials 1.20.1, protocol=763]], favicon=Optional[Favicon[iconBytes=[B@6c94fdfe]], enforcesSecureChat=false, forgeData=Optional[ServerStatusPing[channels={thirst:main=ChannelData[res=thirst:main, version=0.1.1, required=false], comforts:main=ChannelData[res=comforts:main, version=1, required=false], some_assembly_required:main=ChannelData[res=some_assembly_required:main, version=1, required=false], architectury:network=ChannelData[res=architectury:network, version=1, required=true], jei:channel=ChannelData[res=jei:channel, version=1.0.0, required=true], aether:main=ChannelData[res=aether:main, version=1, required=false], minecraft:unregister=ChannelData[res=minecraft:unregister, version=FML3, required=true], l2library:main=ChannelData[res=l2library:main, version=1, required=false], puzzleslib:1=ChannelData[res=puzzleslib:1, version=1, required=true], nitrogen_internals:main=ChannelData[res=nitrogen_internals:main, version=1, required=false], journeymap:version=ChannelData[res=journeymap:version, version=1, required=true], pasterdream:pasterdream=ChannelData[res=pasterdream:pasterdream, version=1, required=false], curios:main=ChannelData[res=curios:main, version=1, required=false], worldinfo:world_id=ChannelData[res=worldinfo:world_id, version=1, required=true], appleskin:sync=ChannelData[res=appleskin:sync, version=1, required=true], constructionwand:main=ChannelData[res=constructionwand:main, version=1, required=false], journeymap:admin_req=ChannelData[res=journeymap:admin_req, version=1, required=true], journeymap:mp_options_req=ChannelData[res=journeymap:mp_options_req, version=1, required=true], journeymap:waypoint=ChannelData[res=journeymap:waypoint, version=1, required=true], forge:tier_sorting=ChannelData[res=forge:tier_sorting, version=1.0, required=false], spectrelib:main=ChannelData[res=spectrelib:main, version=1, required=true], exposure:packets=ChannelData[res=exposure:packets, version=1, required=false], torcherino:channel=ChannelData[res=torcherino:channel, version=2, required=false], journeymap:admin_save=ChannelData[res=journeymap:admin_save, version=1, required=true], journeymap:player_loc=ChannelData[res=journeymap:player_loc, version=1, required=true], showcaseitem:main=ChannelData[res=showcaseitem:main, version=1, required=false], journeymap:teleport_req=ChannelData[res=journeymap:teleport_req, version=1, required=true], epicfight:network_manager=ChannelData[res=epicfight:network_manager, version=1, required=false], armourers_workshop:play=ChannelData[res=armourers_workshop:play, version=f, required=false], easyanvils:1=ChannelData[res=easyanvils:1, version=1, required=false], journeymap:common=ChannelData[res=journeymap:common, version=1, required=true], cuisinedelight:main=ChannelData[res=cuisinedelight:main, version=1, required=false], minecraft:register=ChannelData[res=minecraft:register, version=FML3, required=true], forge:split=ChannelData[res=forge:split, version=1.1, required=true], journeymap:perm_req=ChannelData[res=journeymap:perm_req, version=1, required=true], twilightforest:channel=ChannelData[res=twilightforest:channel, version=2, required=false], geckolib:main=ChannelData[res=geckolib:main, version=1, required=false], jade:networking=ChannelData[res=jade:networking, version=1, required=true]}, mods={easyanvils=8.0.1, equipment_standard=1.4.2, ftblibrary=2001.1.4, geckolib=4.3.1, aether=1.20.1-1.0.0-beta.2.2-neoforge, jei=15.2.0.27, wom=20.1.7.36.1, pasterdream=0.3.1.0, neat=OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱, doapi=1.2.8, epicfight=20.6.3, journeymap=OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱, comforts=6.3.4+1.20.1, mixinextras=0.2.0-beta.9, bookshelf=, vinery=1.4.7, bedspreads=6.2.0+1.20.1, chat_heads=, jeresources=OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱, exposure=1.1.1, puzzlesaccessapi=, forge=ANY, twilightforest=4.3.1893, terraform=7.0.1, minecraft=1.20.1, farmersdelight=1.20.1-1.2.3, enchdesc=OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱, jade=OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱, spectrelib=0.13.14+1.20.1, curios=5.3.5+1.20.1, some_assembly_required=1.20.1-4.0.0, torcherino=20.0.0, armourers_workshop=2.0.10, ftbultimine=2001.1.2, inventoryhud=3.4.18, thirst=1.3.5, fruitstack=1.20.1-1.7.6, cumulus_menus=1.20.1-1.0.0-beta.1-neoforge, constructionwand=1.20.1-2.11, architectury=9.1.12, appleskin=2.5.1+mc1.20.1, showcaseitem=1.20.1-1.0, yet_another_config_lib_v3=3.2.2, arclight=OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱, puzzleslib=8.1.11, nitrogen_internals=1.20.1-0.3.0-neoforge, l2library=2.4.14, crabbersdelight=1.1.3a, cuisinedelight=1.1.11, everyxhotpot=1.1.2BF2-1.20.1-TeaCon2023}, fmlNetworkVer=3, truncated=false]]]
    cachedStatus=<null>
  ]

**Comment by stephan-gh** [comment]
Are you sure you're using the right ProtocolLib version? Try the latest release (5.1.0) for 1.20.1, not the development builds.

**Comment by Cloudwhile** [comment]
[Console]: ProtocolLib version 5.1.0

**Comment by stephan-gh** [comment]
I'm extremely confused about the error you posted in https://github.com/Minecrell/ServerListPlus/issues/407#issuecomment-1871187487, since this doesn't seem to be a native Spigot build. There are mentions of Forge and https://github.com/IzzelAliz/Arclight...

**Comment by Cloudwhile** [comment]
Only [this error](https://hastebin.com/share/ecabukebah.php) occurs when the server has no players.

**Comment by Cloudwhile** [comment]
This does seem to be a error caused by arclight, where constantly refreshing the server list causes the client to crash.

**Comment by Cloudwhile** [comment]
In Mohist also cant work.
[Detail](https://hastebin.com/share/olifarohud.php)
