### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for ServerListPlus

### ISSUE THREAD

**Issue by mibby** [Minecrell/ServerListPlus#53]
Using dev build 254 - ServerListPlusBukkit-3.4-SNAPSHOT.jar version. http://ci.minecrell.net/job/ServerListPlus/254/

Downgrading to dev build 247. No errors.
http://ci.minecrell.net/job/ServerListPlus/247/
```
[13:56:26] [Netty Server IO #3/ERROR]: [ServerListPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for ServerListPlus
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin.getRequest(BukkitPlugin.java:228) ~[ServerListPlusBukkit-3.4-SNAPSHOT.jar:?]
	at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketReceiving(ProtocolLibHandler.java:66) ~[ServerListPlusBukkit-3.4-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:639) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:606) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:300) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:266) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:513) [ProtocolLib.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:246) [ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at net.minecraft.server.v1_8_R1.LegacyPingHandler.channelRead(SourceFile:94) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at net.minecrell.serverlistplus.bukkit.core.player.JSONIdentificationStorage.resolve(JSONIdentificationStorage.java:79) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.core.ServerListPlusCore.resolveClient(ServerListPlusCore.java:186) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.core.ServerListPlusCore.createRequest(ServerListPlusCore.java:190) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin$2.load(BukkitPlugin.java:114) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin$2.load(BukkitPlugin.java:111) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	... 37 more
[13:56:26] [Netty Server IO #0/ERROR]: [ServerListPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for ServerListPlus
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin.getRequest(BukkitPlugin.java:228) ~[ServerListPlusBukkit-3.4-SNAPSHOT.jar:?]
	at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketReceiving(ProtocolLibHandler.java:66) ~[ServerListPlusBukkit-3.4-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:639) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:606) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:300) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:266) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:513) [ProtocolLib.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:246) [ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at net.minecraft.server.v1_8_R1.LegacyPingHandler.channelRead(SourceFile:94) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-8a983f9-9ae3381]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at net.minecrell.serverlistplus.bukkit.core.player.JSONIdentificationStorage.resolve(JSONIdentificationStorage.java:79) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.core.ServerListPlusCore.resolveClient(ServerListPlusCore.java:186) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.core.ServerListPlusCore.createRequest(ServerListPlusCore.java:190) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin$2.load(BukkitPlugin.java:114) ~[?:?]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin$2.load(BukkitPlugin.java:111) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[spigot.jar:git-Spigot-8a983f9-9ae3381]
	... 37 more
[13:56:26] [Netty Server IO #0/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R1.PacketHandshakingInSetProtocol@174f7dad[
    a=47
    b=server-ip
    c=25565
    d=STATUS
  ]

[13:56:26] [Netty Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R1.PacketHandshakingInSetProtocol@256f3a03[
    a=47
    b=server-ip
    c=25565
    d=STATUS
  ]
```

**Comment by Minecrell** [comment]
Uh, I broke it I remember. I'll fix this soon. For now use the previous working version.

**Comment by mibby** [comment]
Sure thing. Just thought I'd let you know. :)

**Comment by Minecrell** [comment]
@mibby I think this should fix it, not completely sure. If you can't get it to work comment here again so I can check it a bit closer again :)

**Comment by Somiona** [comment]
This bug still occur on the latest version
