### ISSUE TITLE
Issue with PerWorldPlugin

### ISSUE THREAD

**Issue by TheChampTF** [Minecrell/ServerListPlus#86]
[20:13:34 INFO]: [ServerListPlus] Enabling ServerListPlus v3.4.3
[20:13:35 INFO]: [ServerListPlus] [Core] Reloading configuration...
[20:13:35 INFO]: [ServerListPlus] [Core] Saving configuration...
[20:13:35 WARN]: [ServerListPlus] [Core] Configuration is not enabled, nothing will be changed on the server! Please execute /slp enable to enable the configuration.
[20:13:35 ERROR]: [ServerListPlus] An internal error occurred while loading the core!
java.lang.NullPointerException
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin.reloadCaches(BukkitPlugin.java:362) ~[ServerListPlus-3.4.3-Universal.jar:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.reloadCaches(ServerListPlusCore.java:182) ~[ServerListPlus-3.4.3-Universal.jar:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:192) ~[ServerListPlus-3.4.3-Universal.jar:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:135) ~[ServerListPlus-3.4.3-Universal.jar:?]
	at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:87) ~[ServerListPlus-3.4.3-Universal.jar:?]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:133) [ServerListPlus-3.4.3-Universal.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins_1.8.8.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[20:13:35 INFO]: [ServerListPlus] Disabling ServerListPlus v3.4.3
[20:13:35 ERROR]: Error occurred while disabling ServerListPlus v3.4.3 (Is it up to date?)
java.lang.NullPointerException
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:151) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins_1.8.8.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecrell.serverlistplus.bukkit.BukkitPluginBase.disablePlugin(BukkitPluginBase.java:46) [ServerListPlus-3.4.3-Universal.jar:?]
	at net.minecrell.serverlistplus.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:140) [ServerListPlus-3.4.3-Universal.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins_1.8.8.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-f04e043-52c7fc0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by Minecrell** [comment]
Update to 3.4.4, this was fixed
